### ISSUE TITLE
Command not showing up on menu.

### ISSUE THREAD

**Issue by gcpeixoto** [fsmMLK/inkscapeCartesianPlotData2D#2]
Hello! 

I have downloaded your extension to try it on Inkscape, but, seemingly, I have a bug. Please take a look on the attached screenshot. I cannot see the launch command in the extension menu. Could you check if there is a problem with the .inx that needs to be fixed or guide me to a solution? 

Thank you and congratulations to your project!

![sshot](https://user-images.githubusercontent.com/1199443/34021374-3df7f6dc-e118-11e7-9957-ea714a18cbba.png)

**Comment by gcpeixoto** [comment]
Hi! 

Sorry! I fixed that! It was missing textext here. 

Anyway, I cannot plot anything... :( Even if using _Values_ or  _File Input_ options, I'm getting an error. I didn't dig into the bug to find out what's really going on with the numpy arrays. Some hint? 

Thanks,

![traceback](https://user-images.githubusercontent.com/1199443/34022691-8022c756-e11f-11e7-990a-820d40316ec2.png)

**Comment by fsmMLK** [comment]
Try to disable LaTeX support and see if it works. If it does work, then the problem is LaTeX related and I can investigate. Let me know your findings.

Please refer to https://fsmmlk.github.io/inkscapeMadeEasy/#installation-and-requirements to see the instructions.

**Comment by fsmMLK** [comment]
Please install package pstoedit and see if it fixes the problem.
